# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Ubisoft.Connect
PackageVersion: 123.0.10520
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
  InstallerSha256: F44050FBA7DEDDB8BC6296EAB6EF3A3D13841E0054F98A864D3D0FDD09C88FB7
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

