# Automatically updated by the winget bot at 2021/Jun/30
PackageIdentifier: SecombaGmbH.Boxcryptor
PackageVersion: 2.47.1745
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: msi
  InstallerUrl: https://www.boxcryptor.com/l/download-windows
  InstallerSha256: 8CAA1CDF355C58F9A3020DC7E6B786C5D0819D45C1D3901979071C4AF2AF7594
  ProductCode: '{04249778-4301-4BA9-9D37-91B56E533A1C}'
ManifestType: installer
ManifestVersion: 1.0.0
