# Automatically updated by the winget bot at 2021/Jun/26
PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.94.781.0
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  InstallerType: exe
  InstallerSha256: DEBE4B58BB77BA9F7DD1AE32A02E6535EE5A8FEB4826354AB929B0DB797649D7
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup.exe
  InstallerType: exe
  InstallerSha256: 9C521B7ACFF2EB7397B4BD4101520AC77764CFF5F22744CE66C01ED34C248615
  Scope: machine
  InstallerSwitches:
    Custom: -norestart ACCEPT_EULA=1
    Silent: -quiet
    SilentWithProgress: -passive
ManifestType: installer
ManifestVersion: 1.0.0
