# Automatically updated by the winget bot at 2021/Jun/28
PackageIdentifier: Belarc.Advisor
PackageVersion: 9.7.0.0
PackageName: Belarc Advisor
Publisher: Belarc Inc.
License: Copyright (c) Belarc Inc.
Moniker: advisor
Tags:
- advisor
- belarc
- benchmark
- info
- profile
- profiling
ShortDescription: The Belarc Advisor builds a detailed profile of your installed software and hardware, network inventory, any missing Microsoft hotfixes, anti-virus status, security benchmarks, and displays the results in your Web browser.
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.belarc.com/advisor/advisorinstaller.exe
  InstallerSha256: 1A1A1050DE58F1C9BF46C8898280AF55E27485C8A5EDF9FFF3009827D96452DA
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
