PackageIdentifier: AltDrag.AltDrag
Publisher: AltDrag
PackageName: AltDrag
Author: Stefan Sundin, Raymond Gillibert
PackageVersion: 1.4
License: GNU General Public License v3.0
InstallerType: nullsoft
LicenseUrl: https://github.com/RamonUnch/AltDrag/blob/main/License.txt
Moniker: altdrag
Tags:
- altdrag
ShortDescription: Easily drag windows when pressing the alt key
PackageUrl: https://github.com/RamonUnch/AltDrag/wiki
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RamonUnch/AltDrag/releases/download/1.44/AltDrag1.44-inst.exe
  InstallerSha256: 0C587691DFD2BB5A65D54EF6B7BE36997EDAB98B55E3AB1D4A0508DA8602A48F
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
