# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: HiBitSoftware.HiBitUninstaller
PackageVersion: 2.6.10.100
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: http://www.hibitsoft.ir/HiBitUninstaller/HiBitUninstaller-setup.exe
  InstallerSha256: 3DBEA0EBFEB4429375B4D05A716179F598D1BCDA573C467F41B259481CD276AF
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
