# Automatically updated by the winget bot at 2021/Jun/23
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 68.104.49222
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 8CC0C4DC676836528F9CD922A27A5AADEC71EFE0B63310F162A7784E731073E4
  ProductCode: "{F868ED3F-22A0-347B-9D9C-218B600DA8F1}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: C71DE9023C2DE0BAE6F3F2929C35170CAC9C4076505C95743F940A21FFE598C9
  ProductCode: "{01AD7176-7135-3C39-919E-F1C88AF7C754}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
