# Automatically updated by the winget bot at 2021/Jun/22
PackageIdentifier: Google.Chrome.Dev
PackageVersion: 68.113.16387
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: 8C36C6C53D0BB2DB5CCD299255DD7FE7D1B7C4D173ECF44F752D015963486BEB
  ProductCode: "{4C326496-F0A3-352D-93FA-371729614025}"
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: 694C8E3D01AD3DC32301BFE85CD833B488E15EE24D4C4DF0E188BEB002A635A5
  ProductCode: "{1E98D3E9-70E4-3AAC-A8CD-193680409770}"
ManifestType: installer
ManifestVersion: 1.0.0
