# Automatically updated by the winget bot at 2021/Jun/25
PackageIdentifier: Amazon.WorkspacesClient
PackageVersion: 3.1.9.2201
PackageName: Amazon WorkSpaces
Publisher: Amazon Web Services, Inc
License: Copyright (c) Amazon Web Services, Inc.
LicenseUrl: https://clients.amazonworkspaces.com/app-terms.html
Moniker: workspaces
Tags:
- amazon
- workspaces
- rdp
ShortDescription: Amazon WorkSpaces offers an easy way to provide a cloud-based desktop experience to your end users.
PackageUrl: https://aws.amazon.com/workspaces/
Installers:
- Architecture: x64
  InstallerUrl: https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
  InstallerSha256: 49128638C36C63A8FE9F68513DFD8C54AD9D619E1D8F376620F7CA2946ECAA53
  InstallerType: msi
  ProductCode: "{317904EA-DB48-47CA-846F-B164EFCA264C}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
